[build]
  # Sadece "npm run build" yeterlidir.
  # package.json içindeki "build" scripti zaten gerekli parametreleri içeriyor.
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/**/*"]