[build]
  # "--" işareti, sonraki argümanların npm yerine "build" script'ine iletilmesini sağlar.
  command = "npm run build -- --no-lint"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/**/*"]